modLoader = "kotlinforforge"
loaderVersion = "[${versions.kotlin_forge},)"
license = "MIT"

[[mods]]
modId = "hexdebug"
version = "${modVersion}"
displayName = "HexDebug"
logoFile = "icon.png"
authors = "object-Object"
description = '''
The HexDebug addon for Hex Casting
'''

[[dependencies.hexdebug]]
modId = "forge"
mandatory = true
versionRange = "[${versions.forge_dependency},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexdebug]]
modId = "minecraft"
mandatory = true
versionRange = "[${versions.minecraft},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexdebug]]
modId = "architectury"
mandatory = true
versionRange = "[${versions.architectury},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexdebug]]
modId = "cloth_config"
mandatory = true
versionRange = "[${versions.cloth_config},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexdebug]]
modId = "hexcasting"
mandatory = true
versionRange = "[${versions.hexcasting_dependency},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexdebug]]
modId = "ioticblocks"
mandatory = true
versionRange = "[${versions.ioticblocks},)"
ordering = "NONE"
side = "BOTH"
